# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Project Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Check typos on source files
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1

      - name: Check MIT license on source files
        uses: korandoru/hawkeye@1574bfcdc2ebae5591783a4c3991a55499bcf2bc # v7.0.1

  checks:
    runs-on: ubuntu-24.04
    needs: lint

    steps:
      - name: Project Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run E2E tests
        run: ./e2e/run.sh
